### ISSUE TITLE
Animals walk on water

### ISSUE THREAD

**Issue by SPiRiT369** [Skandarella/Animal-World#19]
Animals like hare and elephants walk on water, which looks too weird.
Is it possible to fix that behaviour? :)

![Screenshot_20240720_211028](https://github.com/user-attachments/assets/31c22843-cdb1-41c1-8402-a141d062c2bb)

**Comment by Skandarella** [comment]
Since mobs redo by TenPlus1 is not supporting specific floating animations (Only underwater-swimming animations are supported), animals that can naturally swim like hare or elephants, will walk on water. Yes, is looks terribly, but it would not be realistic for those animals not to be able to swim/not to be able to cross the waters.

**Comment by SPiRiT369** [comment]
Oh, this is disappointing, but we can live with that 🤠
Thank you for the answer and for this amazing mod! 🥰
